# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.4.0
_src_path: https://github.com/jupyterlab/extension-template
author_email: loi.hoangthanh.24@gmail.com
author_name: Thanh-Loi Hoang
has_binder: false
has_settings: false
kind: frontend
labextension_name: switch_button
project_short_description: 'A JupyterLab extension: switch button to move notebook.'
python_name: switch_button
repository: ''
test: false

